### ISSUE TITLE
Ошибка при открытии карты onSingleTapUp

### ISSUE THREAD

**Issue by drs88** [yandexmobile/yandexmapkit-android#119]
Изредка при работе программы происходит следующая ошибка во время открытия карты (согласно описанию пользователей). Не могу понять где она может быть, т.к. не представляю как работает данный метод, мб что-то забыл указать или добавить, При загрузке карты добавляются несколько custom объектов наследующих BalloonItem и позиционируется на них. Подскажите хотя бы в какую сторону можно копать.

java.lang.NullPointerException
        at ru.yandex.yandexmapkit.overlay.OverlayItem.getRectBounds(Unknown Source)
        at ru.yandex.yandexmapkit.overlay.Overlay.a(Unknown Source)
        at ru.yandex.yandexmapkit.overlay.Overlay.onSingleTapUp(Unknown Source)
        at ru.yandex.yandexmapkit.OverlayManager.onSingleTapUp(Unknown Source)
        at ru.yandex.yandexmapkit.MapController.onSingleTapUp(Unknown Source)
        at f.onSingleTapUp(Unknown Source)
        at android.view.GestureDetector.onTouchEvent(GestureDetector.java:557)
        at f.a(Unknown Source)
        at ru.yandex.yandexmapkit.MapController.onTouchEvent(Unknown Source)
        at ru.yandex.yandexmapkit.MapSurfaceView.onTouchEvent(Unknown Source)
        at android.view.View.dispatchTouchEvent(View.java:3885)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:942)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:942)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:942)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:942)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:942)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1808)
        at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1141)
        at android.app.Activity.dispatchTouchEvent(Activity.java:2099)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1792)
        at android.view.ViewRoot.deliverPointerEvent(ViewRoot.java:2208)
        at android.view.ViewRoot.handleMessage(ViewRoot.java:1881)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:130)
        at android.app.ActivityThread.main(ActivityThread.java:3706)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:507)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:841)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:599)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by sirekanyan** [comment]
Столкнулся с аналогичной проблемой: **`NullPointerException: Attempt to invoke virtual method 'float ru.yandex.yandexmapkit.utils.ScreenPoint.getX()' on a null object reference`**
```
java.lang.NullPointerException: Attempt to invoke virtual method 'float ru.yandex.yandexmapkit.utils.ScreenPoint.getX()' on a null object reference
	at ru.yandex.yandexmapkit.overlay.OverlayItem.getRectBounds(Unknown Source)
	at ru.yandex.yandexmapkit.overlay.Overlay.a(Unknown Source)
	at ru.yandex.yandexmapkit.overlay.Overlay.onSingleTapUp(Unknown Source)
	at ru.yandex.yandexmapkit.OverlayManager.onSingleTapUp(Unknown Source)
	at ru.yandex.yandexmapkit.MapController.onSingleTapUp(Unknown Source)
	at ru.yandex.ae.onSingleTapUp(Unknown Source)
	at android.view.GestureDetector.onTouchEvent(GestureDetector.java:595)
	at ru.yandex.ae.a(Unknown Source)
	at ru.yandex.yandexmapkit.MapController.onTouchEvent(Unknown Source)
	at ru.yandex.yandexmapkit.MapStaticView.onTouchEvent(Unknown Source)
	at android.view.View.dispatchTouchEvent(View.java:8808)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2581)
        ...
```
