### ISSUE TITLE
Balloon

### ISSUE THREAD

**Issue by jumper0k** [yandexmobile/yandexmapkit-android#122]
Если создать свой layout.xml для унаследованного класа от BalloonItem, основным лэйаутом в layout.xml сделать RelativeLayout, то приложение крэшится при клике на OverlayItem.

```
    java.lang.NullPointerException
    at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:493)
    at android.view.View.measure(View.java:15513)
    at ru.yandex.yandexmapkit.overlay.balloon.BalloonItem.a(Unknown Source)
    at bs.run(Unknown Source)
    at android.os.Handler.handleCallback(Handler.java:725)
    at android.os.Handler.dispatchMessage(Handler.java:92)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:5191)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:562)
    at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Radaykina** [comment]
Кто-то смог решить эту проблему?
 E/ACRA: com.googol.znaetmama.gygolznaetmama_android fatal error : null
                                         java.lang.NullPointerException
                                             at ru.yandex.yandexmapkit.overlay.balloon.BalloonOverlay.a(Unknown Source)
                                             at bt.run(Unknown Source)
                                             at android.os.Handler.handleCallback(Handler.java:725)
                                             at android.os.Handler.dispatchMessage(Handler.java:92)
                                             at android.os.Looper.loop(Looper.java:137)
                                             at android.app.ActivityThread.main(ActivityThread.java:5039)
                                             at java.lang.reflect.Method.invokeNative(Native Method)
                                             at java.lang.reflect.Method.invoke(Method.java:511)
                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
                                             at dalvik.system.NativeStart.main(Native Method)
