### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by Pianov** [yandexmobile/yandexmapkit-android#173]
Добрый день, поймал ошибку:

java.lang.NullPointerException
        at ru.yandex.yandexmapkit.overlay.OverlayItem.getRectBounds(Unknown Source)
        at ru.yandex.yandexmapkit.overlay.Overlay.a(Unknown Source)
        at ru.yandex.yandexmapkit.overlay.Overlay.onSingleTapUp(Unknown Source)
        at ru.yandex.yandexmapkit.OverlayManager.onSingleTapUp(Unknown Source)
        at ru.yandex.yandexmapkit.MapController.onSingleTapUp(Unknown Source)
        at ae.onSingleTapUp(Unknown Source)
        at android.view.GestureDetector.onTouchEvent(GestureDetector.java:569)
        at ae.a(Unknown Source)
        at ru.yandex.yandexmapkit.MapController.onTouchEvent(Unknown Source)
        at ru.yandex.yandexmapkit.MapSurfaceView.onTouchEvent(Unknown Source)
        at android.view.View.dispatchTouchEvent(View.java:7143)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2244)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1949)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2244)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1949)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2244)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1949)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2244)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1949)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2244)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1949)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2244)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1949)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2244)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1949)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2244)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1949)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2244)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1949)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2244)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1949)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2116)
        at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1410)
        at android.app.Activity.dispatchTouchEvent(Activity.java:2408)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2064)
        at android.view.View.dispatchPointerEvent(View.java:7323)
        at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3520)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3454)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4543)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4522)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4618)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:171)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:125)
        at android.os.Looper.loop(Looper.java:140)
        at android.app.ActivityThread.main(ActivityThread.java:5006)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:821)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
        at dalvik.system.NativeStart.main(Native Method)

stdClass Object
(
    [User] => zxliu
    [Brand] => TCT
    [Model] => ALCATEL ONE TOUCH 4030D
    [Product] => Beetle
    [Device] => Beetle_GSM
    [Host] => aclgcl-ubnt244
    [Type] => user
    [Display] => Jelly Bean
    [PhoneModel] => ALCATEL ONE TOUCH 4030D
    [Tags] => release-keys
    [Time] => 1366015287000
    [FingerPrint] => TCT/Beetle/Beetle_GSM:4.1.1/JRO03C/vFH8-0:user/release-keys
    [AndroidVersion] => 4.1.1
    [TotalInternalMemorySize] => 2541166592
    [Board] => Beetle
    [AvailableInternalMemorySize] => 1596588032
)

**Comment by ViHtarb** [comment]
Здравствуйте, столкнулся с такой же ошибкой, хотелось бы узнать, что можно сделать, да бы такого крэша не происходило.

**Comment by scratchboom** [comment]
Несколько раз была такая ошибка в google play логах. Что делать с ней - непонятно

**Comment by sirekanyan** [comment]
Проблема всё ещё актуальна: **`NullPointerException: Attempt to invoke virtual method 'float ru.yandex.yandexmapkit.utils.ScreenPoint.getX()' on a null object reference`**
```
java.lang.NullPointerException: Attempt to invoke virtual method 'float ru.yandex.yandexmapkit.utils.ScreenPoint.getX()' on a null object reference
	at ru.yandex.yandexmapkit.overlay.OverlayItem.getRectBounds(Unknown Source)
	at ru.yandex.yandexmapkit.overlay.Overlay.a(Unknown Source)
	at ru.yandex.yandexmapkit.overlay.Overlay.onSingleTapUp(Unknown Source)
	at ru.yandex.yandexmapkit.OverlayManager.onSingleTapUp(Unknown Source)
	at ru.yandex.yandexmapkit.MapController.onSingleTapUp(Unknown Source)
	at ru.yandex.ae.onSingleTapUp(Unknown Source)
	at android.view.GestureDetector.onTouchEvent(GestureDetector.java:595)
	at ru.yandex.ae.a(Unknown Source)
	at ru.yandex.yandexmapkit.MapController.onTouchEvent(Unknown Source)
	at ru.yandex.yandexmapkit.MapStaticView.onTouchEvent(Unknown Source)
	at android.view.View.dispatchTouchEvent(View.java:8808)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2581)
        ...
```
