### ISSUE TITLE
UnsatisfiedLinkError при инициализации карт

### ISSUE THREAD

**Issue by QuickNickKoenig** [yandexmobile/yandexmapkit-android#185]
На нескольких устройствах с архитектурой armeabi/armeabi-v7a при попытке создать экземпляр MapView происходит крэш.

12-09 12:40:17.771: E/AndroidRuntime(7864): Caused by: java.lang.UnsatisfiedLinkError: Couldn't load cache from loader dalvik.system.PathClassLoader[dexPath=/data/app/my.package-2.apk,libraryPath=/data/app-lib/my.package-2]: findLibrary returned null
12-09 12:40:17.771: E/AndroidRuntime(7864):     at java.lang.Runtime.loadLibrary(Runtime.java:365)
12-09 12:40:17.771: E/AndroidRuntime(7864):     at java.lang.System.loadLibrary(System.java:535)
12-09 12:40:17.771: E/AndroidRuntime(7864):     at ru.yandex.core.CoreApplication.initialize(Unknown Source)
12-09 12:40:17.771: E/AndroidRuntime(7864):     at ru.yandex.core.CoreApplication.initOnce(Unknown Source)
12-09 12:40:17.771: E/AndroidRuntime(7864):     at ru.yandex.yandexmapkit.MapSurfaceView.init(Unknown Source)
12-09 12:40:17.771: E/AndroidRuntime(7864):     at ru.yandex.yandexmapkit.MapSurfaceView.<init>(Unknown Source)
12-09 12:40:17.771: E/AndroidRuntime(7864):     at ru.yandex.yandexmapkit.MapView.<init>(Unknown Source)
12-09 12:40:17.771: E/AndroidRuntime(7864):     ... 31 more

UPD: это произошло после добавления другой нативной либы: я включил RenderScript Support, Build Tools добавили so-файл в директории armeabi-v7a, x86, mips, и после этого приложение прекратило по дефолту обращаться к libcache в папку armeabi.

**Comment by scratchboom** [comment]
Я подложил so файл во все директории с архитектурами и крешиться перестало
