### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by CaxaHbl4** [yandexmobile/yandexmapkit-android#194]
Несколько раз поймал NPE. 
Фиксировалось только на Motorola XT1033 Android version: 5.0.2

<pre>
java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
  	at android.os.Parcel.readException(Parcel.java:1546)
  	at android.os.Parcel.readException(Parcel.java:1493)
  	at android.content.pm.IPackageManager$Stub$Proxy.querySliceContentProviders(IPackageManager.java:2859)
  	at android.app.ApplicationPackageManager.queryContentProviders(ApplicationPackageManager.java:695)
  	at ru.yandex.yandexmapkit.StartupController.fetchStartup(Unknown Source)
  	at ru.yandex.yandexmapkit.StartupController.resume(Unknown Source)
  	at ru.yandex.yandexmapkit.MapController.startAll(Unknown Source)
  	at ru.yandex.yandexmapkit.MapSurfaceView.startAll(Unknown Source)
  	at ru.yandex.yandexmapkit.MapSurfaceView.surfaceCreated(Unknown Source)
  	at android.view.SurfaceView.updateWindow(SurfaceView.java:579)
  	at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:176)
  	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:847)
  	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1986)
  	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1077)
  	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5884)
  	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
  	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
  	at android.view.Choreographer.doFrame(Choreographer.java:550)
  	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
  	at android.os.Handler.handleCallback(Handler.java:739)
  	at android.os.Handler.dispatchMessage(Handler.java:95)
  	at android.os.Looper.loop(Looper.java:135)
  	at android.app.ActivityThread.main(ActivityThread.java:5312)
  	at java.lang.reflect.Method.invoke(Native Method)
  	at java.lang.reflect.Method.invoke(Method.java:372)
  	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
</pre>

**Comment by cheyuriy** [comment]
Та же история возникла после обновления Motorola XT 1058 до 5.1 сегодня.

**Comment by dc-pbelokopytov** [comment]
такая же проблема
