### ISSUE TITLE
Краш на MapView при запуске на Xiaomi Note 3 android 5.0.2

### ISSUE THREAD

**Issue by dimmitriy** [yandexmobile/yandexmapkit-android#220]
Process: package_name, PID: 25845
                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{package_name/activities.MainActivity}: android.view.InflateException: Binary XML file line #8: Error inflating class ru.yandex.yandexmapkit.MapView
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2466)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2528)
                                                                        at android.app.ActivityThread.access$800(ActivityThread.java:169)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                        at android.os.Looper.loop(Looper.java:194)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5552)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:372)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
                                                                     Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class ru.yandex.yandexmapkit.MapView
                                                                        at android.view.LayoutInflater.createView(LayoutInflater.java:637)
                                                                        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:747)
                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:810)
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:508)
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:418)
                                                                        at fragments.child_fragments.SearchMapFragment.onCreateView(SearchMapFragment.java:46)
                                                                        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2074)
                                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104)
                                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1286)
                                                                        at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:758)
                                                                        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1671)
                                                                        at android.support.v4.app.Fragment.performStart(Fragment.java:2096)
                                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1142)
                                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1286)
                                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1268)
                                                                        at android.support.v4.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:2148)
                                                                        at android.support.v4.app.FragmentController.dispatchStart(FragmentController.java:212)
                                                                        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:625)
                                                                        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1228)
                                                                        at android.app.Activity.performStart(Activity.java:5991)
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2429)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2528) 
                                                                        at android.app.ActivityThread.access$800(ActivityThread.java:169) 
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                        at android.os.Looper.loop(Looper.java:194) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5552) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759) 
                                                                     Caused by: java.lang.reflect.InvocationTargetException
                                                                        at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                        at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                                                                        at android.view.LayoutInflater.createView(LayoutInflater.java:611)
                                                                        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:747) 
                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:810) 
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:508) 
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:418) 
                                                                        at fragments.child_fragments.SearchMapFragment.onCreateView(SearchMapFragment.java:46) 
                                                                        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2074) 
                                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104) 
                                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1286) 
                                                                        at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:758) 
                                                                        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1671) 
                                                                        at android.support.v4.app.Fragment.performStart(Fragment.java:2096) 
                                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1142) 
                                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1286) 
                                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1268) 
                                                                        at android.support.v4.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:2148) 
                                                                        at android.support.v4.app.FragmentController.dispatchStart(FragmentController.java:212) 
                                                                        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:625) 
                                                                        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1228) 
                                                                        at android.app.Activity.performStart(Activity.java:5991) 
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2429) 
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2528) 
                                                                        at android.app.ActivityThread.access$800(ActivityThread.java:169) 
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                        at android.os.Looper.loop(Looper.java:194) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5552) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759) 
                                                                     Caused by: java.lang.UnsatisfiedLinkError: com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader[DexPathList[[dex file "/data/data/package_name/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/package_name/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/package_name/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/package_name/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/package_name/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/package_name/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/package_name/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/package_name/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/package_name/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/package_name/files/instant-run/dex/slice-slice_0-classes.dex",
07-11 14:54:12.896 25845-25860/package_name W/art: Suspending all threads took: 5.133ms

**Comment by dimmitriy** [comment]
public class SearchMapFragment extends Fragment {

    private static final String CURRENT_LIST = "current_list";
    private MapController mMapController;
    private OverlayManager mOverlayManager;

    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setHasOptionsMenu(true);
    }

    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        return inflater.inflate(R.layout.fragment_search_map, container, false);
    }

    @Override
    public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        MapView mapView = (MapView) view.findViewById(R.id.maps);

        mMapController = mapView.getMapController();
        mOverlayManager = mMapController.getOverlayManager();
        // Disable determining the user's location
        mOverlayManager.getMyLocation().setEnabled(true);

        View fabList = view.findViewById(R.id.fabList);
        fabList.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                ((FragmentMain)getParentFragment()).startChildFragment(CURRENT_LIST);
            }
        });
        View fabLocation = view.findViewById(R.id.fabLocation);
        fabLocation.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                MyLocationOverlay locationOverlay = mOverlayManager.getMyLocation();
                locationOverlay.findMe();
                Rect rectLocation = locationOverlay.getMyLocationItem().getRectBounds();
                float x = rectLocation.exactCenterX();
                float y = rectLocation.exactCenterY();
                Toast.makeText(getActivity().getApplicationContext(), "my location x: " + x + " y: " + y, Toast.LENGTH_SHORT).show();
            }
        });

        View fabScaleIn = view.findViewById(R.id.fabScaleIn);
        fabScaleIn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                mMapController.zoomIn();
            }
        });

        View fabScaleOut = view.findViewById(R.id.fabScaleOut);
        fabScaleOut.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                mMapController.zoomOut();
            }
        });
    }

    @Override
    public void onCreateOptionsMenu(Menu menu, MenuInflater inflater) {
        inflater.inflate(R.menu.menu_map, menu);
        super.onCreateOptionsMenu(menu, inflater);
    }
}

**Comment by dimmitriy** [comment]
<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    tools:context="fragments.child_fragments.SearchMapFragment">

    <ru.yandex.yandexmapkit.MapView
        android:id="@+id/maps"
        android:layout_width="fill_parent"
        android:layout_height="fill_parent"
        android:apiKey="api_key" />

    <LinearLayout
        android:id="@+id/subToolbarMain"
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:background="@color/shadow_center"
        android:orientation="vertical">

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_weight="1"
            android:textColor="@android:color/white"
            android:gravity="bottom"
            android:layout_gravity="center"/>

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_weight="1"
            android:textColor="@android:color/white"
            android:gravity="top"
            android:layout_gravity="center"/>

    </LinearLayout>

    <android.support.design.widget.FloatingActionButton
        android:id="@+id/fbPoligon"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="left|bottom"
        app:srcCompat="@drawable/poligon"
        style="@style/FloatingButtonStyle"/>

    <android.support.design.widget.FloatingActionButton
        android:id="@+id/fabScaleIn"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="right|bottom"
        android:layout_marginBottom="264dp"
        app:srcCompat="@drawable/plus"
        style="@style/FloatingButtonStyle"/>

    <android.support.design.widget.FloatingActionButton
        android:id="@+id/fabScaleOut"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="right|bottom"
        android:layout_marginBottom="184dp"
        app:srcCompat="@drawable/minus"
        style="@style/FloatingButtonStyle"/>

    <android.support.design.widget.FloatingActionButton
        android:id="@+id/fabLocation"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="right|bottom"
        android:layout_marginBottom="104dp"
        app:srcCompat="@drawable/location"
        style="@style/FloatingButtonStyle"/>

    <android.support.design.widget.FloatingActionButton
        android:id="@+id/fabList"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        app:srcCompat="@drawable/list"
        android:scaleType="center"
        android:layout_gravity="right|bottom"
        app:backgroundTint="@color/colorPrimary"
        style="@style/FloatingButtonStyle"/>

</android.support.design.widget.CoordinatorLayout>

**Comment by saint13** [comment]
Пришлите тестовую версию на mksaint13@yandex-team.ru.  Попробуем  воспроизвести данную проблему.

**Comment by beelancrp** [comment]
Та же ошибка. Только еще и на ЛГ не работает!

**Comment by dimmitriy** [comment]
Здравствуйте. Простите что сразу не ответил, вчера выяснил что эта проблема
воспроизводиться на Xiaomi Note 3 только когда к проекту подключена ORM
Realm.

2016-07-17 15:29 GMT+03:00 Illya Bilan <notifications@github.com>:

**Comment by beelancrp** [comment]
Ну у меня на проекте не подключен Realm, и баг этот есть все равно.

**Comment by saint13** [comment]
Попробуй сделать clean и все пересобрать.

17 июля 2016 г. 3:56 PM пользователь "Illya Bilan" <notifications@github.com>
написал:

**Comment by saint13** [comment]
В данном  телефоне используется  MT6795 arm-64, мапкита под него нет. 
Скорее  всего у вас в приложении есть библиотеки с  нативными либами.  

Для решения  данной проблемы  собирайте приложение только  под  abiFilters 'x86', 'armeabi-v7a'
