### ISSUE TITLE
Mapkit + google play services locations

### ISSUE THREAD

**Issue by beelancrp** [yandexmobile/yandexmapkit-android#221]
Есть баг, когда в проекте используется Яндекс меп кит и Google play services Location, выдает ошибку о inflate"е. Приложение крашиться. 
Вопрос, как использовать яндекс + гугл локейшн в одном приложении. (Варианты типа сделай клин и ребилд не предлагать)

**Comment by beelancrp** [comment]
Вот собственно зависимости. Отказаться от гугловской библиотеки не могу, т.к. на ней завязана другая библиотека для пушей.
`dependencies {
    /**
     * First added libs witch migrated from Eclipse
     */
    compile project(':_PoppyView')
    compile project(':_APP_MSG')
    compile project(':swipeToDismissUndoList')
    compile project(':_EditTextFormLibrary')
    compile files('lib/FlurryAnalytics-5.6.0.jar')
    compile files('lib/adjust-android-4.1.3.jar')
    compile 'ru.yandex:yandexmapkit:2.4.2@aar'
    /**
     * Image loaders
     */
    compile 'com.github.bumptech.glide:glide:3.7.0'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.koushikdutta.ion:ion:2.1.7'
    /**
     * Views third party libs
     */
    compile 'fr.baloomba:viewpagerindicator:2.4.2'
    compile 'de.hdodenhof:circleimageview:2.0.0'
    compile 'com.astuetz:pagerslidingtabstrip:1.0.1'
    compile 'com.jakewharton:butterknife:5.1.1'
    compile 'com.mcxiaoke.volley:library:1.0.19'
    compile 'com.loopj.android:android-async-http:1.4.8'
    /**
     * Google's libs
     */
    compile 'com.android.support:support-v4:23.4.0'
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'com.android.support:design:23.4.0'
    compile 'com.android.support:recyclerview-v7:23.4.0'
    compile 'com.google.android.gms:play-services-gcm:8.4.0'
    compile 'com.google.android.gms:play-services-maps:8.4.0'
//    compile 'com.google.android.gms:play-services-location:8.4.0'
    compile 'com.google.android.gms:play-services-analytics:8.4.0'
    /**
     * Insider Chocolife (Pushes, tracking events)
     */
    compile 'com.useinsider:insider:5.1.5'
}`

**Comment by saint13** [comment]
В ближайшее время могу прислать тестовой проект. Если это необходимо.

18 июля 2016 г. 14:53 пользователь "Illya Bilan" <notifications@github.com>
написал:

**Comment by beelancrp** [comment]
Был ы очень признателен. Нужно просто сделать так, что бы при подключенных яндексе и гуглу:
compile 'com.google.android.gms:play-services-location:8.4.0'
compile 'ru.yandex:yandexmapkit:2.4.2@aar'

не было вот этой ошибки:

Binary XML file line #7: Error inflating class ru.yandex.yandexmapkit.MapView
                                                         at android.view.LayoutInflater.createView(LayoutInflater.java:637)
                                                         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:747)
                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:810)
                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:508)
                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:418)
                                                         at chocolife.me.main.FragmentMap.onCreateView(FragmentMap.java:59)
                                                         at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
                                                         at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
                                                         at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
                                                         at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
                                                         at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
                                                         at android.support.v4.view.ViewPager.populate(ViewPager.java:1177)
                                                         at android.support.v4.view.ViewPager.populate(ViewPager.java:1025)
                                                         at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1545)
                                                         at android.view.View.measure(View.java:17561)
                                                         at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:728)
                                                         at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:464)
                                                         at android.view.View.measure(View.java:17561)
                                                         at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
                                                         at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                                                         at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
                                                         at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
                                                         at android.view.View.measure(View.java:17561)
                                                         at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:1075)
                                                         at android.view.View.measure(View.java:17561)
                                                         at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
                                                         at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
                                                         at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
                                                         at android.view.View.measure(View.java:17561)
                                                         at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
                                                         at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                                                         at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
                                                         at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
                                                         at android.view.View.measure(View.java:17561)
                                                         at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
                                                         at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
                                                         at android.view.View.measure(View.java:17561)
                                                         at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
                                                         at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                                                         at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
                                                         at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
                                                         at android.view.View.measure(View.java:17561)
                                                         at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
                                                         at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
                                                         at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2618)
                                                         at android.view.View.measure(View.java:17561)
                                                         at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2045)
                                                         at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1203)
                                                         at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1409)
                                                         at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1091)
                                                         at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5926)
                                                         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:775)
                                                         at android.view.Choreographer.doCallbacks(Choreographer.java:588)
                                                         at android.view.Choreographer.doFrame(Choreographer.java:558)
                                                     	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreograp

Ошибка 100% из-за конфликтов, потому что когда убираю гугл, все работает, ошибка исчезает но появляется ошибка связанная с отсутствием гугловской либы.

Я кстати забыл добавить что баг этот только на телефонах Xaiomi and LG

**Comment by saint13** [comment]
Хорошо договорились. В ближайшее  время выложу проект.

18 июля 2016 г. 15:56 пользователь "Illya Bilan" <notifications@github.com>
написал:

**Comment by beelancrp** [comment]
С вами можно как то связаться? Не в гите? Есть пару вопросов.
Только что просто отдебажил, и пришел к выводу что все таки это не конфликт либ. (во всяком случае не этих) Нужна ваша помощь, ибо сроки по проекту капец как горят, а ошику отловить не могу(

**Comment by saint13** [comment]
mksaint13@yandex-team.ru

**Comment by beelancrp** [comment]
Закрыто. Ошибка не в этом, продолжаю поиски!(
