### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by kazufukurou** [yandexmobile/yandexmapkit-android#253]
Version: 2.5.3
```
Fatal Exception: java.lang.NullPointerException
       at ru.yandex.yandexmapkit.overlay.balloon.BalloonItem.a(Unknown Source)
       at ru.yandex.bv.run(Unknown Source)
       at android.os.Handler.handleCallback(Handler.java:615)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4954)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:798)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:565)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by saint13** [comment]
Можно шаги воспроизведения.

8 февр. 2017 г. 20:59 пользователь "Artyom" <notifications@github.com>
написал:

**Comment by kazufukurou** [comment]
К сожалению не знаю как воспроизвести - взял из Crashlytics, довольно частая ошибка.
