### ISSUE TITLE
MapView  внутри Fragment

### ISSUE THREAD

**Issue by kolipass** [yandexmobile/yandexmapkit-android#75]
Не получается поместить карту во фрагмент.
В фрагменте пишу:
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
            View mainView = inflater.inflate(R.layout.yandex_map, container);  
            return mainView;
}
yandex_map.xml выглядит вот так: 
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              android:layout_width="fill_parent" android:layout_height="fill_parent"
              android:orientation="vertical">
    <ru.yandex.yandexmapkit.MapView
            android:id="@+id/map"
            android:layout_width="fill_parent"
            android:layout_height="fill_parent"
            android:apiKey="мой ключ"
            android:layout_weight="1"
            />
</LinearLayout>

Если yandex_map.xml использовать как setContentView()  у FragmentActivity (как и у Activity), все прекрасно работает. В фрагменте же получаю такую ошибку:

10-08 16:46:42.429: ERROR/AndroidRuntime(5144): FATAL EXCEPTION: main
        java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
        at android.view.ViewGroup.addViewInner(ViewGroup.java:3337)
        at android.view.ViewGroup.addView(ViewGroup.java:3208)
        at android.view.ViewGroup.addView(ViewGroup.java:3165)
        at android.view.ViewGroup.addView(ViewGroup.java:3145)
        at android.support.v4.app.NoSaveStateFrameLayout.wrap(NoSaveStateFrameLayout.java:40)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:875)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1083)
        at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:635)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1431)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:420)
        at android.os.Handler.handleCallback(Handler.java:605)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:4424)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
        at dalvik.system.NativeStart.main(Native Method)

ну и да removeAllViews() у контейнера фрагмента я вызываю.

**Comment by Egorchik4** [comment]
А можно показать полный код, как получилось расположить карту яндекса на фрагменте ?
