### ISSUE TITLE
Тестовый пример не работает

### ISSUE THREAD

**Issue by MKYU** [yandexmobile/yandexmapkit-android#76]
Тестовый пример в новой версии не работает ни на реальном устройстве (Galaxy S II) с версией Андроид 4.0.3, ни на эмуляторе. Похожая проблема описывалась здесь https://github.com/yandexmobile/yandexmapkit-android/issues/49 но решения так и не было показано.

Подробнее: 
- API-ключ подставлен во все  layout, где  используется объект MapView, 
- ресурсы из yandexmapkit-library добавлены в yandexmapkit-sample, 
- библиотека classes.jar подключена, 
- папка armeabi добавлена. 
  Проект собирается под IntelliJ IDEA, предыдущая версия библиотеки (компилируется тоже под IDEA) работает и с тестовым примером и в реальном приложении, новая -нет! 

Тестовый пример компилируется успешно, хоть и ругается, что классы ImageBalloonItem, OverlayGeoCode  "must either be declared abstract or implement abstract method 'compareTo (T)' in 'Comparable' ". Приложение запускается - показывается список тестовых примеров, но при выборе любого из них - выдаёт ошибку:

10-14 16:50:02.086: ERROR/AndroidRuntime(22248): FATAL EXCEPTION: main
        java.lang.RuntimeException: Unable to start activity ComponentInfo{ru.mapkittest/ru.mapkittest.defaultoverlay.DefaultOverlayActivity}: android.view.InflateException: Binary XML file line #6: Error inflating class ru.yandex.yandexmapkit.MapView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1968)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1993)
        at android.app.ActivityThread.access$600(ActivityThread.java:127)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1159)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:4507)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
        at dalvik.system.NativeStart.main(Native Method)
        Caused by: android.view.InflateException: Binary XML file line #6: Error inflating class ru.yandex.yandexmapkit.MapView
        at android.view.LayoutInflater.createView(LayoutInflater.java:606)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:680)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:739)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
        at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:271)
        at android.app.Activity.setContentView(Activity.java:1835)
        at ru.mapkittest.defaultoverlay.DefaultOverlayActivity.onCreate(DefaultOverlayActivity.java:42)
        at android.app.Activity.performCreate(Activity.java:4465)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1052)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1932)
        ... 11 more
        Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.constructNative(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
        at android.view.LayoutInflater.createView(LayoutInflater.java:586)
        ... 22 more
        Caused by: java.lang.NoClassDefFoundError: ru.yandex.yandexmapkit.R$string
        at ck.a(Unknown Source)
        at ru.yandex.yandexmapkit.MapController.<init>(Unknown Source)
        at ru.yandex.yandexmapkit.MapSurfaceView.init(Unknown Source)
        at ru.yandex.yandexmapkit.MapSurfaceView.<init>(Unknown Source)
        at ru.yandex.yandexmapkit.MapView.<init>(Unknown Source)
        ... 25 more

**Comment by naeimrezaeian** [comment]
Как подключить yandex карты к приложению в Android Studio ?
